framework:
    exceptions:
        Cicada\Frontend\Framework\Captcha\Exception\CaptchaInvalidException:
            log_level: notice
        Cicada\Frontend\Theme\Exception\ThemeException:
            log_level: notice
        Cicada\Frontend\Theme\Exception\ThemeAssignmentException:
            log_level: notice
